import React from 'react';
import { Sparkles, Clock, PlayCircle, Download, BrainCircuit, Clapperboard } from 'lucide-react';

export default function SummaryView({ data, timeline, videoId }) {
  if (!data) return null;

  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const handleTimeClick = (time) => {
    if (videoId) {
      window.open(`https://www.youtube.com/watch?v=${videoId}&t=${Math.floor(time)}s`, '_blank');
    }
  };

  const handleDownload = () => {
    const content = [
      `VIDEO SUMMARY - YT Intelligence`,
      `==============================\n`,
      `THE SUMMARY:`,
      `---------`,
      data.summary || 'No summary available.',
      `\nKEY INSIGHTS:`,
      `-------------`,
      ...(data.key_points?.map((p, i) => `${i + 1}. ${p}`) || ['No key points available.']),
      `\nTIMELINE OVERVIEW:`,
      `------------------`,
      ...(timeline?.map(t => `[${formatTime(t.time)}] ${t.label}`) || ['No timeline available.']),
      `\nGenerated by YT Summarizer Intelligence`
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Summary_${videoId || 'video'}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full h-full space-y-6 animate-fade-in-up">
      <div className="glass-card rounded-[2.5rem] p-8 md:p-10 overflow-hidden relative group h-full aurora-border">
        {/* Header Section */}
        <div className="relative flex flex-col sm:flex-row sm:items-center justify-between gap-6 mb-10 border-b border-white/10 pb-8">
          <div className="flex items-center gap-5">
            <div className="premium-gradient p-4 rounded-2xl shadow-[0_0_30px_rgba(139,92,246,0.3)]">
              <Clapperboard className="w-8 h-8 text-white" />
            </div>
            <div>
              <h2 className="text-3xl font-black text-yellow-300 tracking-tight text-glow-primary">Video Analytics</h2>
              <p className="text-textMuted font-bold tracking-widest text-[9px] uppercase opacity-60">Semantic Processing Engine</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            {timeline && timeline.length > 0 && (
              <div className="hidden md:flex items-center gap-2 px-4 py-2 rounded-xl bg-white/5 border border-white/10 text-[9px] font-black text-primary tracking-widest uppercase">
                <span className="w-2 h-2 rounded-full bg-primary animate-pulse" />
                Live Context
              </div>
            )}
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white/5 border border-white/10 text-[10px] font-black text-white tracking-widest uppercase hover:bg-primary hover:border-primary transition-all group/dl"
            >
              <Download size={14} className="group-hover/dl:-translate-y-0.5 transition-transform" />
              Download TXT
            </button>
          </div>
        </div>

        {/* Content Section */}
        <div className="flex flex-col gap-10">
          {/* Executive Summary */}
          <section className="space-y-4">
            <div className="flex items-center gap-3">
              <div className="h-6 w-1 bg-primary rounded-full shadow-[0_0_10px_rgba(20,184,166,0.6)]" />
              <h3 className="text-xl font-bold text-white uppercase tracking-wider">The Summary</h3>
            </div>
            <p className="text-lg text-textMain leading-relaxed font-medium whitespace-pre-line">
              {data.summary || "Generating abstract..."}
            </p>
          </section>

          {/* Key Takeaways */}
          {data.key_points && data.key_points.length > 0 && (
            <section className="space-y-4">
              <div className="flex items-center gap-3">
                <div className="h-6 w-1 bg-secondary rounded-full shadow-[0_0_10px_rgba(34,211,238,0.6)]" />
                <h3 className="text-xl font-bold text-white uppercase tracking-wider">Key Insights</h3>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {data.key_points.map((point, idx) => (
                  <div key={idx} className="p-4 rounded-xl bg-white/[0.03] border border-white/5 flex gap-4 group/item hover:bg-white/[0.06] transition-all duration-300">
                    <span className="flex-shrink-0 w-8 h-8 rounded-lg bg-white/5 flex items-center justify-center border border-white/10 text-secondary font-black text-xs">
                      {idx + 1}
                    </span>
                    <p className="text-base text-textMuted group-hover/item:text-textMain transition-colors duration-300 font-semibold">
                      {point}
                    </p>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* Timeline Section */}
          {timeline && timeline.length > 0 && (
            <section className="space-y-4">
              <div className="flex items-center gap-3">
                <div className="h-6 w-1 bg-accent rounded-full shadow-[0_0_10px_rgba(139,92,246,0.6)]" />
                <h3 className="text-xl font-bold text-white uppercase tracking-wider">Timeline</h3>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 max-h-[500px] overflow-y-auto pr-2 custom-scrollbar">
                {timeline.map((item, idx) => (
                  <button
                    key={idx}
                    onClick={() => handleTimeClick(item.time)}
                    className="flex items-center gap-4 p-3.5 rounded-xl bg-white/[0.02] border border-white/5 hover:bg-white/[0.08] hover:border-primary/40 group/time transition-all duration-300 text-left w-full"
                  >
                    <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-black/40 border border-white/10 text-primary font-mono font-black text-sm group-hover/time:bg-primary group-hover/time:text-white transition-all">
                      <Clock size={14} className="stroke-[2.5px]" />
                      {formatTime(item.time)}
                    </div>
                    <span className="text-md font-semibold text-textMuted group-hover/time:text-textMain transition-colors flex-1 truncate">
                      {item.label}
                    </span>
                    <PlayCircle size={20} className="text-primary opacity-0 group-hover/time:opacity-100 transition-all" />
                  </button>
                ))}
              </div>
            </section>
          )}
        </div>
      </div>
    </div>
  );
}
